### ISSUE TITLE
CCProgressTimer renders incorrectly

### ISSUE THREAD

**Issue by motek80** [mono/cocos2d-xna#131]
Something is wrong with rendering logic of CCProgressTimer. Setting "Bar" type renders is as kind of flipped triangle; setting it as "Radial" renders it as a bar combined with flipped triangle...

**Comment by kjpou1** [comment]
motek

There are multiple tests for this in the Tests under ProgressActionTests.  Could you tell us the platform you are running this on and if the Tests work for you.  If it is different from the tests then we would need to see some code to actually test that case.

**Comment by motek80** [comment]
Hi,
Thank you for your response. I succeeded to understand whats going wrong:

In my application, sometimes I prefer to use XNA directly. I doing the following: I deriving from CCNode, and inside "Draw" method I calling to XNA stuff (e.g. SpriteBatch.Draw...). This way I making kind of "user control" - I adding this object to layer - and it being rendered.

 So - if I making any SpriteBatch.Draw call before CCProgressTimer (e.g. my "user control" added to layer before CCProgressTimer ) - CCProgressTimer  rendered corrupted.

FYI

**Comment by motek80** [comment]
P.S. Platform = WP8

**Comment by kjpou1** [comment]
motek

Thank you for letting us know and glad that you got this worked out.  I am going to mark this as closed.

Thank you for your feedback and issue reporting.
