### ISSUE TITLE
Please exclude LibTiff from Cocos2d WinRT project

### ISSUE THREAD

**Issue by alexsorokoletov** [mono/cocos2d-xna#143]
This DLL is not required for Cocos2d.WinRT to build but having this dll referenced fails certification (WACK tool)

Error Found: The supported APIs test detected the following errors:◦API System.IO.FileMode in MSCORLIB, PUBLICKEYTOKEN=B77A5C561934E089 is not supported for this application type. BitMiracle.LibTiff.NET.dll calls this API.
◦API System.IO.FileAccess in MSCORLIB, PUBLICKEYTOKEN=B77A5C561934E089 is not supported for this application type. BitMiracle.LibTiff.NET.dll calls this API.
◦API System.IO.File in MSCORLIB, PUBLICKEYTOKEN=B77A5C561934E089 is not supported for this application type. BitMiracle.LibTiff.NET.dll calls this API.
◦API System.IO.FileStream in MSCORLIB, PUBLICKEYTOKEN=B77A5C561934E089 is not supported for this application type. BitMiracle.LibTiff.NET.dll calls this API.
◦API System.IO.FileShare in MSCORLIB, PUBLICKEYTOKEN=B77A5C561934E089 is not supported for this application type. BitMiracle.LibTiff.NET.dll calls this API.
◦API System.Console in MSCORLIB, PUBLICKEYTOKEN=B77A5C561934E089 is not supported for this application type. BitMiracle.LibTiff.NET.dll calls this API.
◦API System.Text.Encoding.GetString(System.Byte[]) in MSCORLIB, PUBLICKEYTOKEN=B77A5C561934E089 is not supported for this application type. BitMiracle.LibTiff.NET.dll calls this API.
◦API System.IO.File.Open(System.String,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare) in MSCORLIB, PUBLICKEYTOKEN=B77A5C561934E089 is not supported for this application type. BitMiracle.LibTiff.NET.dll calls this API.
◦API System.IO.File.Open(System.String,System.IO.FileMode,System.IO.FileAccess) in MSCORLIB, PUBLICKEYTOKEN=B77A5C561934E089 is not supported for this application type. BitMiracle.LibTiff.NET.dll calls this API.
◦API System.IO.Stream.Close in MSCORLIB, PUBLICKEYTOKEN=B77A5C561934E089 is not supported for this application type. BitMiracle.LibTiff.NET.dll calls this API.
◦API System.Console.WriteLine(System.String) in MSCORLIB, PUBLICKEYTOKEN=B77A5C561934E089 is not supported for this application type. BitMiracle.LibTiff.NET.dll calls this API.
◦API System.Console.get_Error in MSCORLIB, PUBLICKEYTOKEN=B77A5C561934E089 is not supported for this application type. BitMiracle.LibTiff.NET.dll calls this API.
◦API System.IO.TextWriter.Write(System.String,System.Object) in MSCORLIB, PUBLICKEYTOKEN=B77A5C561934E089 is not supported for this application type. BitMiracle.LibTiff.NET.dll calls this API.
◦API System.IO.FileInfo in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.FileStream in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.FileSystemInfo in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.FileAttributes in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.DirectoryInfo in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.File in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.FileMode in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.FileAccess in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.FileShare in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.Directory in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.PathTooLongException in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.FileInfo.#ctor(System.String) in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.FileSystemInfo.get_Exists in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.FileSystemInfo.get_CreationTime in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.FileSystemInfo.get_LastAccessTime in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.FileSystemInfo.get_LastWriteTime in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.FileInfo.get_Length in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.FileSystemInfo.get_Attributes in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.DirectoryInfo.#ctor(System.String) in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.File.Create(System.String) in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.File.Open(System.String,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare) in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.File.Exists(System.String) in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.Path.GetFullPath(System.String) in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.Directory.Exists(System.String) in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.Directory.CreateDirectory(System.String) in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.Stream.Close in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.FileStream.#ctor(System.String,System.IO.FileMode,System.IO.FileAccess) in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.String.Format(System.String,System.Object) in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.FileStream.get_Name in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.String.Format(System.String,System.Object,System.Object) in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.File.Delete(System.String) in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.Path.GetTempFileName in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.File.Move(System.String,System.String) in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.File.Copy(System.String,System.String,System.Boolean) in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.String.Format(System.String,System.Object,System.Object,System.Object) in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.Path.Combine(System.String,System.String) in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.PathTooLongException.#ctor in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.Directory.GetFiles(System.String) in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.
◦API System.IO.Directory.GetDirectories(System.String) in MSCORLIB, PUBLICKEYTOKEN=7CEC85D7BEA7798E is not supported for this application type. ICSharpCode.SharpZipLib.dll calls this API.

•Impact if not fixed:  Using an API that is not part of the Windows SDK for Windows Store apps violates the Windows Store certification requirements.

**Comment by kjpou1** [comment]
This should be done now.  Reference commit https://github.com/mono/cocos2d-xna/commit/6e154cf0a4971ecc473d66ab660f6701f8819504

**Comment by alexsorokoletov** [comment]
Amazing, thanks!
Actually,  ICSharpCode.SharpZipLib.dll  also is an issue for W8 Store apps. I excluded it locally and CCParticleSystem part that was referencing I changed to

  var zipInputStream = new GZipInputStream(new MemoryStream(dataBytes));
            if (zipInputStream.CanRead) {
