### ISSUE TITLE
Type Safety - CCActionManager

### ISSUE THREAD

**Issue by kjpou1** [mono/cocos2d-xna#19]
Look into introducing CCAction instead of generic object

**Comment by totallyeviljake** [comment]
CCActionmanager uses a list of HashElement instances. That HashElement class has the CCAction ref in it plus many more items that are used by the manager to manage the list of actions. I looked at removing some of the 'generic' nature of the class but did not see where it would benefit.

**Comment by kjpou1** [comment]
Totally agree.  Looked at it last week and came to the same conclusion.  Am thinking of closing this out.

The only thing I was thinking was the object being passed in some of the methods.

The object references used to be CCObject's and was hoping maybe to replace those with something else.  Considering CCNodes.  More beneficial overall probably not but was just thinking type safety as they used to be CCObject's.
