### ISSUE TITLE
LabelTest Crash

### ISSUE THREAD

**Issue by kjpou1** [mono/cocos2d-xna#26]
Can not remember if this was happening before so may be a regression.

Third test fails because can not find content 

originalAssetName   "fonts/bitmapFontTest2.fnt"

Marked as only iOS and Mac as do not have access to Windows right now.

**Comment by totallyeviljake** [comment]
Did the name of the output DLL change again? It should be cocos2d-xna.dll.

**Comment by kjpou1** [comment]
Have not checked yet.  Just got in and will see what is happening.

**Comment by totallyeviljake** [comment]
Could not find ContentTypeReader Type. Please ensure the name of the Assembly that contains the Type matches the assembly in the full type name: Microsoft.Xna.Framework.Content.ReflectiveReader`1[[cocos2d.CCObject, cocos2d-xna, Version=2.0.3.0, Culture=neutral, PublicKeyToken=null]] (Microsoft.Xna.Framework.Content.ReflectiveReader`1[[cocos2d.CCObject, cocos2d-xna]])

**Comment by totallyeviljake** [comment]
all of the content will need to be regenerated now that the base CCObject class is gone. The embedded types are all different now.

**Comment by kjpou1** [comment]
Oh man that was not good.  I was just looking at the error myself and was going to comment the same thing.

**Comment by kjpou1** [comment]
Although I do not think it is all the content.  Fonts are a definite though.

**Comment by totallyeviljake** [comment]
all fonts, plists, and tmx files. massive push just went up and I also included the content builder project this time.

**Comment by kjpou1** [comment]
Wow!!  Nice Jake!!!!!  Thanks for that.

**Comment by totallyeviljake** [comment]
This is working again on the mac. closing.

**Comment by kjpou1** [comment]
This seems to have hosed the iOS project.  Nothing shows up now.

**Comment by totallyeviljake** [comment]
looks like it is stuck in an infinite look on the node.visit() during the main loop.

**Comment by totallyeviljake** [comment]
Checked this against an older version of the tests and the font warnings upon startup are expected:

Apr  2 13:01:48 jacobs-iPhone cocos2dtests[16014] <Warning>: GL_IMG_texture_compression_pvrtc
Apr  2 13:01:48 jacobs-iPhone cocos2dtests[16014] <Warning>: 
Apr  2 13:01:48 jacobs-iPhone cocos2dtests[16014] <Warning>: Can't find Arial-24, going to try using Arial instead.
Apr  2 13:01:48 jacobs-iPhone cocos2dtests[16014] <Warning>: Can't find Arial-24, going to try using Arial instead.
Apr  2 13:01:48 jacobs-iPhone cocos2dtests[16014] <Warning>: Can't find Arial-24, going to try using Arial instead.
Apr  2 13:01:48 jacobs-iPhone cocos2dtests[16014] <Warning>: cocos2d : getActionByTag: Target not found

**Comment by kjpou1** [comment]
Yes the warnings are normal or at least they have always been there since I started.

Your commit of the older fonts for iOS fixed the issue.  Thanks
