### ISSUE TITLE
Bring project in line with MonoTouch Bindings

### ISSUE THREAD

**Issue by kjpou1** [mono/cocos2d-xna#29]
MonoTouch Bindings examples are CCAction 

Start in place of StartWithTarget.

CCAction

```
    public virtual void StartWithTarget(CCNode target)
    {
        m_pOriginalTarget = m_pTarget = target;
    }
```

MonoTouch Bindings CCAction

```
[Export ("startWithTarget:")]
    void Start (CCNode target);
```

**Comment by kjpou1** [comment]
Oh by the way this was just a suggestion not something we should do and probably low priority.

**Comment by totallyeviljake** [comment]
The bindings are for the DLL binary of cocos2d-x,right?

**Comment by kjpou1** [comment]
Yes the bindings are for the DLL binary.  I only took a look at the first couple of ones out there when looking at the chipmunk bindings the other day.
