### ISSUE TITLE
Some transitions do not have a background to transition into.

### ISSUE THREAD

**Issue by kjpou1** [mono/cocos2d-xna#4]
Example is PageTurn. The page is flipping but the underlying background is colored and all of a sudden it appears.

Issue being discussed here: https://github.com/totallyevil/cocos2d-xna/issues/67

**Comment by totallyeviljake** [comment]
So this one actually does work, but what you are seeing is the destination page UNDER the turning page. You have to really look close on a phone to see it, but on the surface tablet you can plainly see the underside of the page turn. Of course, that's NOT quite what you would want if you are implementing a page turning book, but the page turn is working.

The desired behavior would be to not show the next scene on the backside of the page? Hmm, not sure.

**Comment by kjpou1** [comment]
Maybe using XNA you see the second page but with MG the second page does not show up until the page turning effect is complete.  The underside of the page can be a separate issue if it really is an issue like for turning a book page but still does not show up with MG.

**Comment by totallyeviljake** [comment]
what platform of MonoGame? I was using MonoGame on Surface RT when I saw the underpage showing. Maybe it's a blending problem on MacOS?

**Comment by kjpou1** [comment]
Android, iOS and Mac

**Comment by kjpou1** [comment]
I have found the problem in MG for this not working like it does for XNA.

In GraphicsDevice SetRenderTarget there are two lines of code that clears the RenderTarget if the usage is set to DiscardContents.

Lines 1722 thru 1725.

If we comment out the lines 1724 and 1725 then all the transitions work.

```
        // In XNA 4, because of hardware limitations on Xbox, when
        // a render target doesn't have PreserveContents as its usage
        // it is cleared before being rendered to.
        //if (clearTarget)
            //Clear(DiscardColor);
```

But what is the real fix?  Is this true for XBox?

**Comment by kjpou1** [comment]
Ok it looks like the fix is actually here at line 1627 when we are actually un setting the render target.

```
            //clearTarget = true;
```

If we comment out that line then all the transitions are still working.

**Comment by totallyeviljake** [comment]
this change is in MonoGame?

**Comment by kjpou1** [comment]
yes in GraphicsDevice SetRenderTarget in MG

**Comment by kjpou1** [comment]
See see https://github.com/mono/MonoGame/issues/1739 and https://github.com/mono/MonoGame/pull/1738
