### ISSUE TITLE
Dropping Legacy Code - CCZone

### ISSUE THREAD

**Issue by kjpou1** [mono/cocos2d-xna#6]
- CCZone

Can be safely killed

**Comment by kjpou1** [comment]
@totallyeviljake I do not see a reason for CCZone really.  Could you give a little background on it and it's raison d'etre.  Maybe you have an idea for it and I need to look a little more closely at the code which is why I am starting with the CCObject Copy first.

**Comment by kjpou1** [comment]
Ok have now modified my opinion on CCZone.  I now see why it is being used and how.  This actually goes hand in hand with the CCObject discussion on issue #5.  These two are inter-twined.

**Comment by totallyeviljake** [comment]
I honestly think CCZone was the cocos2d-x way of doing autoboxing. It's just a bag class intended to hold a CCObject. Probably some deep thinking and hard core refactoring could get rid of CCZone entirely. It seems to be very inefficient in the .NET runtime. It probably makes much more sense in an unmanaged runtime like C++.

**Comment by kjpou1** [comment]
After the CCObject elimination I think we can start seeing the Forest.  CCZone now takes an ICopyable instead of CCObject.  We should be able to eliminate the CCZone altogether now and change the CopyWithZone to just plain Copy (ICopyable copyMe);

**Comment by kjpou1** [comment]
Have this done but want to do a little more tests before a PR.
